[package]
name = "gosh"
version = "1.2.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cod = "3.1"
dirs = "4.0.0"
liner = { git = "https://github.com/Kyllingene/liner" }